server:
  port: 8083

spring:
  application:
    name: acg-rating-service

  datasource:
    # Docker 内通过 mysql 容器名访问
    url: jdbc:mysql://mysql:3306/acg_rating_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "00000712"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    nacos:
      discovery:
        # Docker 内使用 nacos 容器名
        server-addr: nacos:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        health-check-url: /actuator/health
        ephemeral: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      catalogService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

jwt:
  secret: "MySuperSecureJwtSecretKeyForHS256_123456"
  expiration: 86400000